# Generated by Django 6.0.3 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskgroup_alter_task_options_task_taskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
